#!/usr/bin/env ruby
# frozen_string_literal: true

require 'rainbow'
require_relative './routes/selection_routes'
require_relative './models/Pages'
require_relative './Loggin'

loggin
main_page = Page.find('Vim cursor')
main_page.cursor = Routes.menu(main_page) until main_page.cursor.nil?

print "\e[H\e[2J"
